package com.andgate.ikou.constants



const val SLIDE_SPEED = TILE_SPAN * 15.0f / 1.0f // units per second

const val ROUGH_SLIDE_DISTANCE = TILE_SPAN // units
const val ROUGH_SLIDE_INITIAL_SPEED = SLIDE_SPEED
const val ROUGH_SLIDE_FINAL_SPEED = 0f
const val ROUGH_SLIDE_AVERAGE_SPEED = (ROUGH_SLIDE_FINAL_SPEED + ROUGH_SLIDE_INITIAL_SPEED) / 2.0f
const val ROUGH_SLIDE_TIME = ROUGH_SLIDE_DISTANCE / ROUGH_SLIDE_AVERAGE_SPEED
const val ROUGH_SLIDE_DECCELERATION = (ROUGH_SLIDE_FINAL_SPEED - ROUGH_SLIDE_INITIAL_SPEED) / ROUGH_SLIDE_TIME // units per second per second

const val FALL_SPEEDUP_FACTOR = 4.0f
const val FALL_DISTANCE = FLOOR_SPACING
const val FALL_SPEED_INITIAL = FALL_DISTANCE / 1.0f // units per second
const val FALL_SPEED_FINAL = FALL_SPEED_INITIAL * FALL_SPEEDUP_FACTOR // units per second
const val FALL_SPEED_AVERAGE = (FALL_SPEED_INITIAL + FALL_SPEED_FINAL) / 2.0f // units per second
const val FALL_TIME = FALL_DISTANCE / FALL_SPEED_AVERAGE // seconds
const val FALL_ACCELERATION = (FALL_SPEED_FINAL - FALL_SPEED_INITIAL) / FALL_TIME // units per second per second